[databases]
* = host=127.0.0.1 port=5432

[pgbouncer]
logfile = /var/log/postgresql/pgbouncer.log
pidfile = /var/run/postgresql/pgbouncer.pid
listen_addr = *
listen_port = 6432
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt
admin_users = yashp, postgres

# Pool configuration (Transaction Mode)
pool_mode = transaction
max_client_conn = 150
default_pool_size = 15
min_pool_size = 0
reserve_pool_size = 5
reserve_pool_timeout = 5

# Timeout and connection tuning
query_timeout = 120
client_idle_timeout = 30
server_lifetime = 1200
server_idle_timeout = 60
idle_transaction_timeout = 10
